#!/usr/bin/env python3
"""Build a compact diagnostic figure for the OPSD cross-source audit."""
from __future__ import annotations
import argparse
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IN = ROOT / "results" / "opsd_cross_source_strict_v5"

METHODS = ("network_lp", "fixed_recovery", "myopic_recovery", "energy_only")
LABELS = {
    "network_lp": "AC-bound LP",
    "fixed_recovery": "Fixed recovery",
    "myopic_recovery": "Myopic recovery",
    "energy_only": "Constant-bound counterfactual",
}
COLORS = {
    "network_lp": "#0072B2",
    "fixed_recovery": "#D55E00",
    "myopic_recovery": "#009E73",
    "energy_only": "#7F7F7F",
}

def run(in_dir: Path = DEFAULT_IN) -> None:
    # Read the canonical bootstrap table generated by
    # build_opsd_cross_source_statistics.py.  Keeping one table avoids
    # silently producing a second RNG/order-dependent interval set.
    summary_path = in_dir / "date_cluster_summary.csv"
    if not summary_path.is_file():
        raise FileNotFoundError(f"canonical summary is missing: {summary_path}")
    summary = pd.read_csv(summary_path).rename(columns={
        "ci_low": "ci_low_kw", "ci_high": "ci_high_kw",
    })
    required = {"site", "method", "estimate_kw", "ci_low_kw", "ci_high_kw"}
    missing = required - set(summary.columns)
    if missing:
        raise ValueError(f"canonical summary is missing columns: {sorted(missing)}")
    # CSV type inference turns numeric site labels into floats.  Normalize the
    # labels before pivoting/reindexing so the panel cannot silently become
    # empty when the policy-row site labels are strings.
    summary["site"] = summary["site"].astype(str)
    summary["method"] = summary["method"].astype(str)
    if summary.duplicated(["site", "method"]).any():
        dup = summary.loc[summary.duplicated(["site", "method"], keep=False), ["site", "method"]]
        raise ValueError(f"canonical summary has duplicate site/method rows:\n{dup.to_string(index=False)}")
    if not set(summary["method"]).issubset(METHODS):
        unknown = sorted(set(summary["method"]) - set(METHODS))
        raise ValueError(f"canonical summary has unknown methods: {unknown}")
    numeric = summary[["estimate_kw", "ci_low_kw", "ci_high_kw"]].to_numpy(float)
    if not np.isfinite(numeric).all():
        raise ValueError("canonical summary contains NaN or infinite estimates/intervals")
    if ((summary["ci_low_kw"] > summary["estimate_kw"]) |
            (summary["estimate_kw"] > summary["ci_high_kw"])).any():
        raise ValueError("canonical summary has an invalid confidence interval")
    sites = list(sorted(summary["site"].unique()))
    pivot = summary.pivot(index="site", columns="method", values="estimate_kw").reindex(sites)
    missing_cells = pivot.reindex(columns=METHODS).isna()
    if missing_cells.any().any():
        raise ValueError(
            "canonical summary is incomplete after site normalization:\n"
            f"{missing_cells[missing_cells].stack().index.tolist()}"
        )
    pivot = pivot.reindex(columns=METHODS)
    ratio = pivot["network_lp"] / pivot["energy_only"]
    if not np.isfinite(ratio.to_numpy(float)).all() or (ratio <= 0).any():
        raise ValueError("network/constant-bound ratios are not finite and positive")
    ratio_frame = pd.DataFrame({"site": ratio.index, "network_to_constant_bound": ratio.values})
    ratio_frame.to_csv(in_dir / "network_to_constant_bound_ratio.csv", index=False)

    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.size": 10, "axes.labelsize": 11, "axes.titlesize": 11,
                         "legend.fontsize": 8.5, "xtick.labelsize": 10, "ytick.labelsize": 10,
                         "pdf.fonttype": 42, "ps.fonttype": 42})
    x = np.arange(len(sites), dtype=float)
    fig, axes = plt.subplots(1, 2, figsize=(10.2, 4.2), constrained_layout=True,
                             gridspec_kw={"width_ratios": [1.55, 1.0]})
    ax = axes[0]
    offsets = np.linspace(-0.27, 0.27, len(METHODS))
    for off, method in zip(offsets, METHODS):
        sub = summary[summary.method == method].set_index("site").reindex(sites)
        if sub[["estimate_kw", "ci_low_kw", "ci_high_kw"]].isna().any().any():
            raise ValueError(f"NaN after reindex for method={method!r}; check canonical site labels")
        y = sub.estimate_kw.to_numpy(float)
        lo = y - sub.ci_low_kw.to_numpy(float)
        hi = sub.ci_high_kw.to_numpy(float) - y
        ax.errorbar(x + off, y, yerr=np.vstack([lo, hi]), fmt="o", ms=5.5,
                    lw=1.4, capsize=2.5, color=COLORS[method], label=LABELS[method])
    ax.set_xticks(x, sites)
    ax.set_xlabel("Battery placement (IEEE-13 bus.phase)")
    ax.set_ylabel("Repeated-service endpoint (kW)")
    ax.set_title("A. OPSD held-out profiles")
    ax.grid(axis="y", color="#D9D9D9", linewidth=.7, alpha=.8)
    ax.set_axisbelow(True)
    ax.legend(loc="upper left", frameon=False, ncol=2, columnspacing=1.0,
              handletextpad=0.4, borderaxespad=0.3)

    ax = axes[1]
    # Ratio is a descriptive point estimate; show the two placement bars.
    vals = ratio.to_numpy(float)
    bars = ax.bar(np.arange(len(sites)), vals, color=[COLORS["network_lp"]] * len(sites), width=.58)
    ax.axhline(1.0, color="#555555", lw=.9, ls="--")
    ax.set_xticks(np.arange(len(sites)), sites)
    ax.set_ylim(0, max(1.02, float(np.max(vals) * 1.25)))
    ax.set_ylabel("Network / constant-bound")
    ax.set_title("B. Retained fraction")
    ax.grid(axis="y", color="#D9D9D9", linewidth=.7, alpha=.8)
    ax.set_axisbelow(True)
    for bar, value in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width() / 2, value + .025, f"{value:.1%}", ha="center", va="bottom", fontsize=9)
    fig.savefig(in_dir / "opsd_cross_source_frontier.pdf", bbox_inches="tight")
    fig.savefig(in_dir / "opsd_cross_source_frontier.png", dpi=220, bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--in-dir", type=Path, default=DEFAULT_IN)
    args = parser.parse_args()
    run(args.in_dir)
