#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export PYTHONPATH="$ROOT/src"
python "$ROOT/scripts/process_ausgrid.py"
python "$ROOT/scripts/build_ausgrid_scenarios.py"
python "$ROOT/scripts/run_pilot.py"
python "$ROOT/scripts/run_ausgrid_pilot.py"
python "$ROOT/scripts/process_opsd.py"
python "$ROOT/scripts/build_opsd_scenarios.py"
python "$ROOT/scripts/run_opsd_pilot.py"
python "$ROOT/scripts/build_pilot_figures.py"
python "$ROOT/scripts/build_event_tree_figure.py"
python "$ROOT/scripts/build_baseline_table.py"
echo "Pilot outputs written under $ROOT/results and $ROOT/figures"
